name: Build Debug APK

on:
  workflow_dispatch:    # با این گزینه می‌تونی دستی از گوشی اجرا کنی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout کد
      uses: actions/checkout@v4

    - name: نصب Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: دادن اجازه به gradlew
      run: chmod +x ./gradlew

    - name: ساخت APK (debug)
      run: ./gradlew assembleDebug

    - name: آپلود APK
      uses: actions/upload-artifact@v4
      with:
        name: 8ballpool-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
